<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Differences-between-lists-and-NumPy-Arrays" data-toc-modified-id="Differences-between-lists-and-NumPy-Arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Differences between lists and NumPy Arrays</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Multidimensional-Arrays" data-toc-modified-id="Multidimensional-Arrays-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Multidimensional Arrays</a></span></li><li><span><a href="#Example-of-1D-array" data-toc-modified-id="Example-of-1D-array-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Example of 1D-array</a></span></li><li><span><a href="#Example-of-2D-array" data-toc-modified-id="Example-of-2D-array-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Example of 2D-array</a></span></li><li><span><a href="#Axis-wise-operation-on-ndarray" data-toc-modified-id="Axis-wise-operation-on-ndarray-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Axis wise operation on ndarray</a></span></li><li><span><a href="#Numpy-also-provides-many-functions-to-create-arrays:" data-toc-modified-id="Numpy-also-provides-many-functions-to-create-arrays:-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Numpy also provides many functions to create arrays:</a></span></li><li><span><a href="#Array-slicing" data-toc-modified-id="Array-slicing-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Array slicing</a></span></li><li><span><a href="#Integer-array-indexing" data-toc-modified-id="Integer-array-indexing-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Integer array indexing</a></span></li><li><span><a href="#Boolean-array-indexing:" data-toc-modified-id="Boolean-array-indexing:-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Boolean array indexing:</a></span></li><li><span><a href="#Datatypes" data-toc-modified-id="Datatypes-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Datatypes</a></span></li><li><span><a href="#Numpy-array-math" data-toc-modified-id="Numpy-array-math-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>Numpy array math</a></span><ul class="toc-item"><li><span><a href="#add()" data-toc-modified-id="add()-2.10.1"><span class="toc-item-num">2.10.1&nbsp;&nbsp;</span>add()</a></span></li><li><span><a href="#subtract()" data-toc-modified-id="subtract()-2.10.2"><span class="toc-item-num">2.10.2&nbsp;&nbsp;</span>subtract()</a></span></li><li><span><a href="#multiply()" data-toc-modified-id="multiply()-2.10.3"><span class="toc-item-num">2.10.3&nbsp;&nbsp;</span>multiply()</a></span></li><li><span><a href="#divide()" data-toc-modified-id="divide()-2.10.4"><span class="toc-item-num">2.10.4&nbsp;&nbsp;</span>divide()</a></span></li><li><span><a href="#np.sqrt()" data-toc-modified-id="np.sqrt()-2.10.5"><span class="toc-item-num">2.10.5&nbsp;&nbsp;</span>np.sqrt()</a></span></li><li><span><a href="#dot()" data-toc-modified-id="dot()-2.10.6"><span class="toc-item-num">2.10.6&nbsp;&nbsp;</span>dot()</a></span></li><li><span><a href="#sum()" data-toc-modified-id="sum()-2.10.7"><span class="toc-item-num">2.10.7&nbsp;&nbsp;</span>sum()</a></span></li></ul></li><li><span><a href="#Numpy-array-manipulation" data-toc-modified-id="Numpy-array-manipulation-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>Numpy array manipulation</a></span><ul class="toc-item"><li><span><a href="#Transpose" data-toc-modified-id="Transpose-2.11.1"><span class="toc-item-num">2.11.1&nbsp;&nbsp;</span>Transpose</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-2.11.2"><span class="toc-item-num">2.11.2&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-2.11.3"><span class="toc-item-num">2.11.3&nbsp;&nbsp;</span>reshape</a></span></li></ul></li></ul></li></ul></div>

# Introduction to Numpy


NumPy is the core library for scientific computing in Python. It provides a high-performance multi-dimensional array object, and tools for working with these arrays. 

To use NumPy, we first need to `import` the `numpy` package:

In [96]:
import numpy as np      # syntax to import the numpy where np can be used as short name from numpy
np.__version__          # tells about the version of the numpy package

'1.18.1'

## Differences between lists and NumPy Arrays
* An array's size is immutable.  You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [datatype](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html).
* A NumPy array behaves in a Pythonic fashion.  You can `len(my_array)` just like you would assume.

In [99]:
lst = [4.0, 3.286, 3]
print(lst)

[4.0, 3.286, 3]


In [100]:
# Can have elements appended to it
lst.append(4.0)
print(lst)

# Can have multiple datatypes in it.
lst.insert(1, "Whatevs")
print(lst)

# Can have items removed
lst.pop(1)
print(lst)

[4.0, 3.286, 3, 4.0]
[4.0, 'Whatevs', 3.286, 3, 4.0]
[4.0, 3.286, 3, 4.0]


In [101]:
ary = np.array(lst)    # this is called typecast from list to numpy array
print(ary)   

[4.    3.286 3.    4.   ]


In [102]:
ary.dtype       # returns datatype of the array

dtype('float64')

In [103]:
ary.itemsize    # number of bytes required to store each element in the array

8

In [104]:
ary.size       # total number of elements

4

In [105]:
len(ary)       # returns length of array

4

In [106]:
ary.nbytes     # total number of bytes required to store the array

32

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a `tuple` of integers giving the size of the array along each dimension.


### Multidimensional Arrays
* The data structure is actually called `ndarray`, having the dimension $n\times d$
* Arrays can have multiple dimensions, you declare them on creation.
* Dimensions of an array help to define that what each element in the array represents. For example, A two dimensional array is just an array of arrays.
* **Rank** defines how many dimensions an array contains (The number of axes is rank)
* **Shape** defines the length of each of the array's dimensions
* Each dimension is also referred to as an **axis**, and they are zero-indexed. Multiples are called **axes**.
* A 2d array is AKA **matrix**.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

### Example of 1D-array

In [107]:
ary1 = np.array([1, 2, 3])    # Create a rank 1 array
print(type(ary1))             # prints type of array

<class 'numpy.ndarray'>


In [108]:
print('Shape of the array is ',ary1.shape)

Shape of the array is  (3,)


In [109]:
print('Values are: ',ary1[0], ary1[1], ary1[2])   #

Values are:  1 2 3


In [114]:
ary1[0] = 0      # Change an element of the array
print(ary1)

[0 2 3]


### Example of 2D-array

In [115]:
ary2 = np.array([[1, 2, 3],
                 [4, 5, 6]], np.float16)
print(ary2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [116]:
ary2.ndim    # returns dimensionality of the ndarray

2

In [117]:
ary2.shape   # retuns shape of the ndarray in tuple

(2, 3)

In [118]:
ary2.size    # returns number of elements in ndarray

6

In [119]:
len(ary2)    # returns first dimension of the ndarray

2

In [120]:
ary2.itemsize   # number of bytes required to store individual elements of ndarray

2

In [121]:
%whos

Variable       Type       Data/Info
-----------------------------------
arr_r2         ndarray    2x3: 6 elems, type `int64`, 48 bytes
ary            ndarray    4: 4 elems, type `float64`, 32 bytes
ary1           ndarray    3: 3 elems, type `int64`, 24 bytes
ary2           ndarray    2x3: 6 elems, type `float16`, 12 bytes
gpas           ndarray    3: 3 elems, type `float64`, 24 bytes
gpas_as_list   list       n=3
lst            list       n=4
np             module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [122]:
%whos ndarray

Variable   Type       Data/Info
-------------------------------
arr_r2     ndarray    2x3: 6 elems, type `int64`, 48 bytes
ary        ndarray    4: 4 elems, type `float64`, 32 bytes
ary1       ndarray    3: 3 elems, type `int64`, 24 bytes
ary2       ndarray    2x3: 6 elems, type `float16`, 12 bytes
gpas       ndarray    3: 3 elems, type `float64`, 24 bytes


In [124]:
ary2[1]

array([4., 5., 6.], dtype=float16)

In [126]:
ary2[1][2]

6.0

In [127]:
ary2[1,2]

6.0

### Axis wise operation on ndarray

In [212]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], np.float16)

In [213]:
a.mean()   # verify with your hand calculation

3.5

In [214]:
a.mean(axis=1)    # verify with your hand calculation

array([2., 5.], dtype=float16)

### Numpy also provides many functions to create arrays:

In [130]:
arr = np.zeros((2,))  # Create an array of all zeros
print(arr)

[0. 0.]


In [131]:
arr = np.zeros((2,2))  # Create an array of all zeros
print(arr)

[[0. 0.]
 [0. 0.]]


In [132]:
arr = np.ones((1,2))   # Create an array of all ones
print(arr)

[[1. 1.]]


In [133]:
arr = np.full((2,2), 7) # Create a constant array
print(arr)

[[7 7]
 [7 7]]


In [134]:
arr = np.eye(2) # Create a 2x2 identity matrix
print(arr)

[[1. 0.]
 [0. 1.]]


In [135]:
arr = np.random.random((2,2)) # Create an array filled with random values
print(arr)

[[0.23240835 0.7694425 ]
 [0.02353896 0.77297152]]


### Array slicing
**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multi-dimensional, you must specify a slice for each dimension of the array:

In [145]:
import numpy as np

a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [146]:
print(a[0, 1])
b[0, 0] = 77         # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array.

In [147]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])   # Create the following rank 2 array with shape (3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [148]:
row_r1 = a[1, :]        # Rank 1 view of the second row of a
row_r2 = a[1:2, :]      # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [149]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [151]:
a = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

print(a[[0, 1, 2],
        [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [21]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing: 

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [169]:
a = np.array([[1,2], [3,4], [5,6]])

bool_idx = a > 2   # this returns a numpy array of Booleans of the same shape as a,
                   # where each slot of bool_idx tells whether that element of a is > 2.'''

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [171]:
# Assignment with condition
a[a > 2] = 0
print(a)

[[1 2]
 [0 0]
 [0 0]]


For brevity, we have left out a lot of details about numpy array indexing; if you want to know more, you should read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. 

| datatype | value range |
|----|---|
| int8  |	Byte (-128 to 127)|
|int16	| Integer (-32768 to 32767)|
|int32  |	Integer (-2147483648 to 2147483647)|
|int64	|Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	| Unsigned integer (0 to 255)|
|float32|	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64|	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex64	|Complex number, represented by two 32-bit floats (real and imaginary components)|



Here is an example:

In [173]:
x = np.array([1, 2])                  # Let numpy choose the datatype
y = np.array([1.0, 2.0])              # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int32


You can read all about numpy datatypes in the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Numpy array math

Basic mathematical functions operate element-wise on arrays, and are available both as operator overloads and as functions in the numpy module:

#### add()

In [175]:
x = np.array([[1,2], [3,4]], dtype=np.float32)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Element-wise sum; both produce the array
print(x + y)
z = np.add(x, y)

[[ 6.  8.]
 [10. 12.]]


In [177]:
z.dtype      # convert to higher datatype

dtype('float64')

#### subtract()

In [178]:
# Element-wise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


#### multiply()

In [179]:
# Element-wise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


#### divide()

In [180]:
# Element-wise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### np.sqrt()

In [181]:
# Element-wise square root; produces the array
print(np.sqrt(x))

[[1.        1.4142135]
 [1.7320508 2.       ]]


#### dot()

We use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [185]:
x = np.array([[1,2], [3,4]])    
y = np.array([[5,6], [7,8]])    

v = np.array([9,10])            
w = np.array([11,12])           

In [186]:
# Inner product of vectors;
print(v.dot(w))
print(np.dot(v, w))

219
219


In [187]:
# Matrix / vector product;
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [188]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### sum()

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [189]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

### Numpy array manipulation

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

#### Transpose

In [195]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [35]:
v = np.array([[1,2,3]])

print(v) 
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


#### Broadcasting

Broadcasting is a powerful mechanism that allows `numpy` to work with arrays of different shapes when performing arithmetic operations.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [207]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for idx, _ in np.ndenumerate(x):
    y[idx, :] = x[idx, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [208]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [209]:
y = x + vv  # Add x and vv element-wise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [210]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [41]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [42]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [43]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [44]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [45]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

#### reshape

In [199]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [203]:
np.reshape(a, (2, 3))        # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
np.ravel(a) 

array([0, 1, 2, 3, 4, 5])

In [205]:
np.reshape(np.ravel(a), (2, 3)) 

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

If you are already familiar with MATLAB, you might find this [tutorial](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) useful to get started with NumPy.